config/routes.rb
Rails.application.routes.draw do
  # scope "(:lang)", lang: /en|tw|jp/ do
  scope "(:lang)", locale: /en|tw/ do
    resources :products do
      collection do
        get :my
      end
      resources :comments, shallow: true, only:[:create, :destroy]
      # member do
      #   patch :like
      # end
    end

    resources :orders, only: [:create]

    # /api
    namespace :api do
      namespace :v1 do
        resources :products, only: [] do
          member do
            # /api/v1/products/id/like
            patch :like
            patch :sort
          end
        end
      end
    end

    #resources :comments, only: [:show, :edit, :update, :destroy]

    resource :users, except: [:destory] do
      collection do
        get :sign_in
      end
    end

    resource :sessions, only: [:create, :destroy]
    resource :cart, only: [:show, :create, :destroy] do
      collection do
        get :checkout
      end
    end
    # get '/users/sign_in', to: 'users#sign_in'


    # get "/products/new", to: "products#new", as: :new_product
    # post "/products", to: "products#create"
    # get '/products', to: 'products#index'
    # get '/products/:id', to: 'products#show', as: :product
    # patch '/products/:id', to: 'products#update'
    # delete '/products/:id', to: 'products#destroy'
    # get '/products/:id/edit', to: 'products#edit', as: :edit_product
    get "/search", to: "products#search"
    get "/about", to: "pages#about", as: :about
    get "/privacy", to: "pages#privacy", as: :privacy
    root "products#index"
  end
end

app/views/shared/_flash.html.erb
<% [:notice, :alert].each do |type| %>
<div>
      <% if flash[type] %>
      <div data-controller="flash" class="flash-<%= type %> flex items-center justify-between">
            <%= flash[type] %>
            <button data-action="flash#close" class="bg-white text-black px-2 rounded" >X</button>
      </div>
      <% end %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="flex items-center justify-center">
  <ul class="flex gap-2">
    <li><%= link_to "English", url_for(lang: :en) %></li>
    <li><%= link_to "中文", url_for(lang: :tw) %></li>
    <li><%= link_to "日文", url_for(lang: :jp) %></li>
  </ul>
  <div>
    <%= Time.current.year %>&copy; 墨韻坊
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="flex items-center justify-between px-3 py-2 text-white bg-slate-800">
  <div class="flex items-center gap-2">
  
    <h1 class="text-2xl font-bold">
      <%= link_to t('navbar.name') , root_path %>
    </h1>
    <section class="flex items-center gap-2">
      <ul class="flex gap-3">
        <li>
          <%= link_to t('navbar.products') , products_path%>
        </li>
        <li>
          <%= link_to t('navbar.about') , about_path%>
        </li>
        <li>
          <%= link_to t('navbar.privacy') , privacy_path%>
        </li>
      </ul>
      <form action="/search" data-turbo="false">
        <input type="search" name="q" value="<%= params[:q] %>" class="input input-bordered input-xs text-black">
        <button class="btn btn-xs">搜尋</button>
      </form>
    </section>
  </div>
  <div>
    
    <ul class="flex gap-3">
    <li class="relative items-center mr-4">
      <%= link_to cart_path do %>
        <%
=begin%>
 <%= image_tag "icon/cart.svg", class: "text-white"%> 
<%
=end%>
        <i class="fa-solid fa-cart-shopping fa-xl"></i>
        <% if current_cart.count > 0 %>            
          <span class="absolute badge badge-xs badge-secondary rounded -top-1 -right-2"><%= current_cart.count %></span>
          
        <% end %>
      <% end %>
    </li>
      <% if user_signed_in? %>
        <li><%= current_user.email %></li>
        
        <li>
          <%= link_to t('navbar.logout'), sessions_path, data: { turbo_method: "delete" } %>
        </li>
      <% else %> 
        <li>
          <%= link_to t('navbar.register') , new_users_path %>
        </li>
        <li>
          <%= link_to t('navbar.login') , sign_in_users_path %>
        </li>
      <% end %>
      
    </ul>
  </div>
  <%
=begin%>
 <%= current_cart.cart_items.count %> 
<%
=end%>
</nav>