config/routes.rb
Rails.application.routes.draw do
  # scope "(:lang)", lang: /en|tw|jp/ do
  scope "(:lang)", locale: /en|tw/ do
    resources :products do
      collection do
        get :my
      end
      resources :comments, shallow: true, only:[:create, :destroy]
      # member do
      #   patch :like
      # end
    end

    resources :orders, only: [:create]

    # /api
    namespace :api do
      namespace :v1 do
        resources :products, only: [] do
          member do
            # /api/v1/products/id/like
            patch :like
            patch :sort
          end
        end
      end
    end

    #resources :comments, only: [:show, :edit, :update, :destroy]

    resource :users, except: [:destory] do
      collection do
        get :sign_in
      end
    end

    resource :sessions, only: [:create, :destroy]
    resource :cart, only: [:show, :create, :destroy] do
      collection do
        get :checkout
      end
    end
    # get '/users/sign_in', to: 'users#sign_in'


    # get "/products/new", to: "products#new", as: :new_product
    # post "/products", to: "products#create"
    # get '/products', to: 'products#index'
    # get '/products/:id', to: 'products#show', as: :product
    # patch '/products/:id', to: 'products#update'
    # delete '/products/:id', to: 'products#destroy'
    # get '/products/:id/edit', to: 'products#edit', as: :edit_product
    get "/search", to: "products#search"
    get "/about", to: "pages#about", as: :about
    get "/privacy", to: "pages#privacy", as: :privacy
    root "products#index"
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  # 委任、指定delegate 轉發方法 所以委任對象一定要有該方法才行
  delegate :count, to: :cart_items

  def total_amout
    cart_items.reduce(0) do |acc, item|
      acc + (item.product.price * item.quantity)
    end.to_i
  end

  def add!(t)
    found_item = cart_items.find { |item| item.product == t.product }

    if found_item
      # found_item.update(quantity: found_item.quantity + item.quantity)
      found_item.increment!(:quantity, t.quantity)
    else
      cart_items << t
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include Braintreeable
  # before_action :authenticate_user!
  before_action :find_product, only:[:create]

  def show
  end

  def create
    # 加入購物車
    item = CartItem.new(product: @product, quantity: params[:quantity])
    current_cart.add!(item)
    # current_user.cart.cart_items
    # 轉商品頁
    redirect_to @product, notice: "成功加入購物車"
  end

  def destroy
    current_cart.destroy
    redirect_to root_path, notice: '購物車已清空'
  end

  def checkout
    @order = Order.new
    @token = braintree_gateway.client_token.generate

  end

  private
  def find_product
    @product = Product.find(params[:id])
  end

  # def gateway
  #   Braintree::Gateway.new(
  #     :environment => :sandbox,
  #     :merchant_id => "mshfmqycgyxh3wdw",
  #     :public_key => "rh9st67ck9bwyktk",
  #     :private_key => "140c87c7702e1ae5c79b54e6bd6756a2",
  #   )
  # end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_item.html.erb
<div class="grid gap-2 grid-cols-3 border-slate-500 border-2 rounded p-4 items-center">
  <div class="p-2">
    <figure class="w-28">
      <%= product_cover(item.product) %>
    </figure>
  </div>
  <div>
    <h3 class="text-xl font-bold">
      <%= item.product.title %>
    </h3>
  </div>
  <div class="flex justify-between">
    <div><%= item.quantity %></div>

    <div>
      NT$ <%= item.product.price.to_i%>
    </div>
  </div>
</div>

app/views/carts/checkout.html.erb
<h1 class="text-2xl">結帳</h1>

總計:<%= current_cart.total_amout %>
<section>
  <div class="col-span-2 grid gap-2">
    <%= render partial:'cart_item', collection: current_cart.cart_items, as: :item %>
  </div>
  <aside>
    <h2 class="text-xl">摘要</h2>
    <ul>
      <li>總計:<%= current_cart.total_amout %></li>
    </ul>
  </aside>
</section>
<section>
  <%= form_with model: [@order] do |f| %>
    <div>
      <%= f.label :recipient, '收件人' %>
      <%= f.text_field :recipient, class:'border-2 border-black m-2' %>
    </div>
    <div>
      <%= f.label :address, '地址' %>
      <%= f.text_field :address, class:'border-2 border-black m-2' %>
    </div>
    <div>
      <%= f.label :tel, '電話' %>
      <%= f.text_field :tel, class:'border-2 border-black m-2' %>
    </div>
    <div data-controller="braintree" data-token="<%= @token %>"></div>
    <div><%= f.submit '送出', class: 'btn btn-neutral' %></div>
  <% end %>
</section>

app/views/carts/show.html.erb
<h1 class="text-2xl">購物車</h1>

<section class="grid gap-4 grid-cols-3 ">
  <div class="col-span-2 grid gap-2">
    <%= render partial:'cart_item', collection: current_cart.cart_items, as: :item %>
    <div>
      <%= link_to '清空購物車', cart_path, class: 'ink-btn', data: { turbo_method: 'delete' } %>
    </div>
  </div>
  <aside class="col-span-1">
    <h2 class="text-xl">摘要</h2>
    <ul>
      <li>總計:<%= current_cart.total_amout %></li>
    </ul>
   <%= link_to '結帳', checkout_cart_path, class: 'ink-btn' %>
  </aside>
</section>