config/routes.rb
Rails.application.routes.draw do
  # scope "(:lang)", lang: /en|tw|jp/ do
  scope "(:lang)", locale: /en|tw/ do
    resources :products do
      collection do
        get :my
      end
      resources :comments, shallow: true, only:[:create, :destroy]
      # member do
      #   patch :like
      # end
    end

    resources :orders, only: [:create]

    # /api
    namespace :api do
      namespace :v1 do
        resources :products, only: [] do
          member do
            # /api/v1/products/id/like
            patch :like
            patch :sort
          end
        end
      end
    end

    #resources :comments, only: [:show, :edit, :update, :destroy]

    resource :users, except: [:destory] do
      collection do
        get :sign_in
      end
    end

    resource :sessions, only: [:create, :destroy]
    resource :cart, only: [:show, :create, :destroy] do
      collection do
        get :checkout
      end
    end
    # get '/users/sign_in', to: 'users#sign_in'


    # get "/products/new", to: "products#new", as: :new_product
    # post "/products", to: "products#create"
    # get '/products', to: 'products#index'
    # get '/products/:id', to: 'products#show', as: :product
    # patch '/products/:id', to: 'products#update'
    # delete '/products/:id', to: 'products#destroy'
    # get '/products/:id/edit', to: 'products#edit', as: :edit_product
    get "/search", to: "products#search"
    get "/about", to: "pages#about", as: :about
    get "/privacy", to: "pages#privacy", as: :privacy
    root "products#index"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
  acts_as_list scope: :user

  has_one_attached :cover do |attachable|
    attachable.variant :thumb, resize_to_limit: [300, 300]
  end

  belongs_to :user
  has_many :comments, ->{ order(id: :desc) }

  has_many :like_products
  has_many :liked_users, through: :like_products, source: :user

  validates :title, presence: true
  validates :price, numericality: { greater_than: 0 }

  #scope
  # scope :ok, -> { where(deleted_at: nil) }
  # scope :cheap, -> { where("price <=30") }
  default_scope { where(onsale: true) }

  # def self.search(q)
  #   Product.where("title like ? OR description like ?","%#{q}%","%#{q}%").order(id: :desc)
  # end

  def self.ransackable_attributes(auth_object = nil)
    ["description", "onsale", "price", "title"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  #軟刪除(加上時間戳記)
  # def destroy
  #   update(deleted_at: Time.current)
  # end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  before_action :find_product, only: [:like]
  before_action :find_user_product, only: [:sort]
  before_action :authenticate_user!

  def like
    #加入喜歡
    if current_user.liked?(@product)
      current_user.liked_products.destroy(@product)
      render json: { status: 'unliked'  }
      #移除喜歡
    else
      current_user.liked_products << @product
      render json: { status: 'liked'  }
      #加入喜歡
    end
  end

  def sort
    @product.insert_at(params[:newIndex] + 1)
    render json: {'result':123}
  end

  private
  def find_product
    @product = Product.find(params[:id])
  end

  def find_user_product
    @product = current_user.products.unscope(where: :onsale).find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_owned_product, only: [ :edit, :update, :destroy]

  def new
    @product = Product.new
  end

  def create
    # render html: params
    # 寫入資料庫
    # 顯示"新增成功"
    # 跳轉其他頁面

    #從商品角度新增商品
    #@product = Product.new(product_params)
    #@product.user_id = current_user.id
    #@product.user = current_user

    #從user的角度去新增商品
    @product = current_user.products.new(product_params)
    if @product.save
      # flush[:notice] = '新增商品成功'
      redirect_to root_path, notice: '新增商品成功'
    else
      render :new, alert: '新增商品失敗'
    end
  end

  def index
    # flash[:notice] = "123" 用來寫關閉flash訊息的功能
    @products = Product.includes(:user)
                        .order(id: :desc)
                        .page(params[:page])
                        .per(4)
    # 裝套件才有page和per
    # @products = Product.where(deleted_at: nil).order(id: :desc)
  end

  def search
    # @products = Product.where("title like ? OR description like ?","%#{params[:q]}%","%#{params[:q]}%").order(id: :desc)
    # @products = Product.search(params[:q])
    data = Product.ransack(title_or_description_cont: params[:q], onsale_eq: true)
    @products = data.result
  end

  def show
    # @product = Product.find_by!(id: params[:id])
    # @product = Product.find(params[:id])
    @comment = Comment.new
    @comments = @product.comments
  end

  def my
    @products = current_user.products.unscope(where: :onsale).page(params[:page]).per(4)
  end

  def edit
    #@product = Product.find(params[:id])
  end

  def update
    #@product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to my_products_path(@product), notice: '更新成功'
    else
      render :edit
    end
  end

  def destroy
    #@product = Product.find(params[:id])
    # @product.destroy
    # @product.update(deleted_at: Time.current)
    @product.destroy
    redirect_to root_path, notice: '商品刪除成功'
  end

  private
  # Strong Parameter
  def product_params
    params.require(:product).permit(:title, :description, :price, :onsale, :cover, :publish_date)
  end

  def find_product
    # begin
    @product = Product.find(params[:id])
    # @product = Product.find(params[:id])
    # rescue ActiveRecord::RecordNotFound
      # render html: '查無此資料', status: 404
      # render file: Rails.public_path.join('404.html'),
            # status: 404,
            # status: :not_found,
            # layout: false
    # end
  end

  def find_owned_product
    @product = current_user.products.unscope(:where).find(params[:id])
  end
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_cover(product, variant = :thumb)
    if product.cover.attached?
      image_tag product.cover.variant(variant)
    else
      image_tag "/images/product/default.jpg"
    end
  end
end

app/views/products/_form.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<% if product.errors.any? %>
    <section class="bg-rose-600 my-4 p-4 text-white">
        <ul>
            <% product.errors.full_messages.each do |message| %>
                <li>
                    <%= message %>
                </li>
                <% end %>
        </ul>
    </section>
<% end %>
<%= form_with model: product, data: { turbo: false } do |form|%>
    <div>
        <%= form.label :cover, class:'label' %>
        <%= form.file_field :cover, class:'file-input file-input-sm file-input-bordered w-full max-w-xs' %>
    </div>
    <div>
        <%= form.label :title , class:'label'%>
        <%= form.text_field :title, class: 'input input-bordered input-sm w-full max-w-xs' %>
    </div>
    <div>
        <%= form.label :description , class:'label'%>
        <%= form.text_area :description, class: 'textarea textarea-bordered w-full max-w-xs' %>
    </div>
    <div>
        <%= form.label :price, class:'label'%>
        <%= form.number_field :price, class: 'input input-bordered input-sm w-full max-w-xs' , min: 0 %>
    </div>
    <div>
        <%= form.label :onsale %>
        <%= form.check_box :onsale %>
    </div>
    <div>
        <%= form.label :publish_date , class:'label' %>
        <%= form.text_field :publish_date, data: { controller: "datepicker" },  
                                            class: 'input input-bordered input-sm w-full max-w-xs' %>
    </div>
    <div class="my-4">
        <%= form.submit class: 'btn btn-sm btn-primary'%>
    </div>
<% end %>

app/views/products/_item.html.erb
<%= tag.li data:{ id: product.id }, class:class_names("p-2 border rounded shadow border-slate-300 bg-white", "grayscale": !product.onsale) do %>
  <div>
    <%= link_to edit_product_path(product) do %>
    <figure>
        <%= product_cover(product) %>
    </figure>
    <% end %>
    <h2><%= product.title %></h2>
    <span><%= product.price %></span>
    <p>
        <%= product.description %>
    </p>
  </div>
<% end %>

<!-- li data-id="<%= product.id %>" 
  class="<%= class_names("p-2 border rounded shadow border-slate-300 bg-white", "grayscale": !product.onsale) %>">
    <div>
        <%= link_to edit_product_path(product) do %>
        <figure>
            <%= product_cover(product) %>
        </figure>
        <% end %>
        <h2><%= product.title %></h2>
        <span><%= product.price %></span>
        <p>
            <%= product.description %>
        </p>
    </div>
</li -->

app/views/products/_product.html.erb
<li class="p-2 border rounded shadow border-slate-300">
    <div>
        <%= link_to product_path(product) do %>
        <figure>
            <%= product_cover(product) %>
        </figure>
        <% end %>
        <h2><%= product.title %></h2>
        <span><%= product.price %></span>
        <p>
            <%= product.description %>
        </p>
    </div>
</li>

app/views/products/edit.html.erb
<h1 class='text-2xl my-2'>編輯商品</h1>

<%= render 'form', product: @product%>

app/views/products/index.html.erb
<h1>商品列表</h1>
<%  if user_signed_in? %>
<%= link_to "新增商品", new_product_path, class:'ink-btn' %>
<%= link_to "我的商品", my_products_path, class:'ink-btn' %>
<% end %>

<ul class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
    <%= render @products %>
</ul>
<footer>
    <%= paginate(@products) %> <!--kaminari 套件提供paginate-->    
</footer>

app/views/products/my.html.erb
<h1>已上架商品</h1>
<%= link_to "新增商品", new_product_path, class:'ink-btn' if user_signed_in? %>
<ul class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4" data-controller="drag">
    <%= render partial: 'item', collection: @products, as: :product %>
</ul>

app/views/products/new.html.erb
<h1 class='text-2xl my-2'>新增商品</h1>

<%= render 'form', product: @product%>

app/views/products/search.html.erb
<h1 class="text-2xl">搜尋結果</h1>
<ul class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
    <%= render @products %>
</ul>

app/views/products/show.html.erb
<% if user_signed_in? and current_user.own?(@product)  %>
    <%= link_to '編輯' , edit_product_path(@product), class: 'ink-btn' %>
    <%= link_to '刪除' , product_path(@product), class: 'ink-btn ink-btn-danger' , data: { turbo_method: 'delete' ,
            turbo_confirm: '確定刪除？' } %>
<% end %>


<section class="grid grid-cols-1 gap-3 sm:grid-cols-3">
    <div class="col-span-2">
        <%= image_tag @product.cover.variant(:thumb) if @product.cover.attached? %>
    </div>
    <div class="col-span-1">
        <%= form_with url: cart_path, 
            data: { turbo: false }, 
            class: 'flex flex-col gap-3' do |f| %>
            <%= f.hidden_field :id, value: @product.id %>
            <h2 class="flex items-center gap-2 text-2xl"><%= @product.title %></h2>
            <h3 class="text-xl">售價：<%= @product.price %></h3>

            <div>
                <%= f.select :quantity, (1..10).to_a, {}, class:"border border-slate-500" %>
                
            </div>

            <div class='ink-btn w-full text-center'>
                <%= link_to '收藏','#', data: { 
                    controller: 'like',
                    path: like_api_v1_product_path,
                    liked: current_user&.liked?(@product),
                    action: 'like#toggle',
                    like_target: 'btn'
                } %>
                    
            </div>
            <div>
                <%= f.submit '加入購物車', class: 'ink-btn w-full' %>
            </div>
        <% end %>
    </div>
</section>
    <p>
        <%= simple_format @product.description %>
    </p>
<section>
    <h3 class="text-xl">留言：</h3>
    <%= form_with(model: [@product, @comment]) do |form|%>
        <%= form.text_area :content, class: 'field'%>
        <div>
            <%= form.submit class:"ink-btn" %>
        </div>
    <% end %>
    <ul id="comment_area">
    <% @comments.each do |comment| %>
        <li><%= comment.content %></li>
    <% end %>
    </ul>
</section>